### PR TITLE
Cleanup the swift code

### PR DESCRIPTION
**Pull request by Fokko**
Hi @gilv 

I'm back with a new PR. We're experiencing some performance issues with the Swift object store. Not sure where the problem comes from. We're running a YARN cluster that pulls a lot of data from a SWIFT store. It looks like the http connections aren't fully utilized, but it is still to early to tell where the problems comes from. Did you hear anything?

I've went through the code and fixed some stuff to make it more readable for me, for example:
- Made variables immutable if possible
- Made variables private if possible
- Inline variables to functions
- Add missing @override annotations
- Fixed small typo's in docstring and comments

Kind regards, Fokko

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@Fokko welcome back.. I did not heard about issues where  http connections aren't fully utilized. Did you tried to play with some configuration keys? May be this can make improvement.
I will later merge this pull request, just need to run some tests to see all is working.

**Comment by Fokko** [comment]
Yes I've played with the block size, and the size of the executors. Will keep you posted

**Comment by gilv** [comment]
@Fokko thanks. merged

**Comment by Fokko** [comment]
Thanks @gilv

**Pull request closed without merging**
