### PR TITLE
Fix guava shading

### PR DESCRIPTION
**Pull request by smurphy31**
Fixing the guava shading to match what is in the IAM branches. I also moved the module in the code-checks.xml so everything would compile.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@smurphy31 did you managed to compile the project with the proposed change?

````
my-mac:stocator my$ mvn clean package -Pall-in-one
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.ibm.stocator:stocator >----------------------
[INFO] Building com.ibm.stocator:stocator 1.0.36-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stocator ---
[INFO] Deleting /Users/my/Dev/stocator/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ stocator ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.095 s
[INFO] Finished at: 2019-10-03T10:38:58+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (checkstyle) on project stocator: Failed during checkstyle configuration: LineLength is not allowed as a child in Checker -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
````

**Comment by smurphy31** [comment]
Yes, and in fact for me it did not compile without the checkstyle change, but perhaps I'm using a different version of maven, we're on 3.5.4. I can revert the changes to that file, since it sounds like this is only an issue for me and mine.
```
$ mvn clean package -Pall-in-one
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< com.ibm.stocator:stocator >----------------------
[INFO] Building com.ibm.stocator:stocator 1.0.36-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stocator ---
[INFO] Deleting /Users/mshelley/Documents/cloudPlayground/stocator/target
[INFO]
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ stocator ---
[INFO] Starting audit...
Audit done.
...
```

**Comment by gilv** [comment]
@smurphy31 my maven is  3.6.1

**Comment by smurphy31** [comment]
Reverting the checkstyle seems to cause issues with the CI (it seemed happy before)
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (checkstyle) on project stocator: Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]
```

**Comment by smurphy31** [comment]
Hey @gilv, is there any update on this?

**Comment by gilv** [comment]
@smurphy31 will handle it in the next few days. thanks

**Comment by gilv** [comment]
@smurphy31 merged. thanks

**Pull request closed without merging**
