### PR TITLE
Fixing issues with Glob Filter

### PR DESCRIPTION
**Pull request by guykhazma**
The current GlobFilter code doesn't work well when trying to list a path of the form:
```
cos://mybucket.service/mypath/*.parquet
```
If the objects under this path are starting with `part-`

The reason is because for some reason there is a special case in the glob filter for such case:
```Java
      if (name != null && name.startsWith("part-")) {
        LOG.trace("accept on parent {}, path pattern {}",
            path.getParent().toString(), pathPattern);
        match = FilenameUtils.wildcardMatch(path.getParent().toString() + "/", pathPattern);
      } else {
        match = FilenameUtils.wildcardMatch(pathStr, pathPattern);
      }
```

This PR removes the extra logic and only use:
```Java
match = FilenameUtils.wildcardMatch(pathStr, pathPattern);
```
@gilv what was the reason to have this in the first place?

All of the glob tests pass after this change, in addition I have changed the glob tests to run once for flat listing set to `true` (the default) and once for flat listing set to `true` using parameterized tests (changing the expected results accordingly).
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@guykhazma wow...there was a reason for this and i need to recall it. 
What exactly the problem you see and in which scenario it occur?

**Comment by gilv** [comment]
@guykhazma if user has an object foo.parquet in the mybucket/mydata..and user list mybucket/mydata he need to get back foo.parquet and not foo.parquet/parts-..parquet. Is this somehow related flat listing flag we have in Stocator?

**Comment by guykhazma** [comment]
@gilv not necessarily, it depends on the listing mode.
if the user has flat listing on (the default)- then the listing returns all of the objects in the case above he should get the `part-<something>.parquet` as this is what really matches the wildcard.

if it has the flat listing is off then the listing will return only `foo.parquet` and then it will show up because it matches the wildcard.

**Comment by gilv** [comment]
@guykhazma but the current code is not an issue with Spark+Stocator. So why you need this change? In fact i added this code since there were issues in Spark if it return all parts instead of unified name

**Comment by gilv** [comment]
@guykhazma assume COS has the following data:
```
mybucket/foo/a.parquet/part-1.parquet
mybucket/foo/a.parquet/part-2.parquet
mybucket/foo/a.parquet/_SUCCESS
```
parts are suppose to be hidden from users and users should never use Spark to access parts directly. But only access with unified name "mybucket/foo/a.parquet" or "mybucket/foo/*.parquet". With s3a it works out of the box since it uses directory style listing and will return "a.parquet" to Spark.. but with Stocator access "mybucket/foo/*.parquet" will return all the parts, which is wrong. So to avoid it, we have this filter in Stocator.

**Comment by guykhazma** [comment]
@gilv having `a.parquet` in the path is not a convention so the above will work only if the user chose so.
for example if the user used:
```
df.write.parquet("cos://mybucket.service/mypath")
```

to save the dataset and then he would like to get all of the parquet files under this path, using:
```
cos://mybucket.service/mypath/*.parquet
```

will not work with the current code.
In general the wild card should be applied on the listing that is returned whether it is flat listing or not.
(I would also recommend using flat listing = false by default)

**Comment by gilv** [comment]
@guykhazma if user created df.write.parquet("cos://mybucket.service/mypath") then he should read ("cos://mybucket.service/mypath")  back..not read parts which are hidden.

**Comment by guykhazma** [comment]
@gilv that's not what spark expects, spark enables users to read only some files from a path according to a wildcard.
Stocator shouldn't assume that it reads only data that was written by Spark (there are many such use cases)

**Comment by gilv** [comment]
@guykhazma let's discuss it offline

**Pull request closed without merging**
