### PR TITLE
Close http response to avoid exhausting http pool

### PR DESCRIPTION
**Pull request by airbots**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
Hi @airbots ,
Thanks for submitting the PR. It seems like it's failing the checkstyle.
`/home/travis/build/SparkTC/stocator/src/main/java/com/ibm/stocator/fs/swift/SwiftOutputStream.java:179: Trailing whitespace found.`

**Comment by djalova** [comment]
@airbots The SwiftConnectionManager in the constructor for SwiftOutputStream already returns a CloseableHttpClient, so I'm not sure if this changes any behavior. Is there something in the PR that closes the HttpResponse?

**Comment by airbots** [comment]
Hi @djalova , sorry about the late response. Please check the try-resource feature for java 8: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by airbots** [comment]
The try clause will automatically check null and close the resource. For the check-style, hmmm, I did not see there is any addition white space. Interesting.

**Comment by djalova** [comment]
@airbots Thanks for the link. These changes look good to me.
The white space is on line 179 after the `}`

**Comment by gilv** [comment]
closing this due to lack of activity

**Pull request closed without merging**
