### PR TITLE
Init method improvement

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
@gilv I decided to keep a map of the service name and its client in case the user connects to different services in a single job. I made the method synchronized because all the tasks try to initialize a client at the same time, so the map doesn't get updated.

**Comment by gilv** [comment]
@djalova this is not what i meant in the issue i opened. What you did is caching per task...but in any case each task do init only once, so this pull request provide no improvement. We need to use Singelton pattern, this will be per JVM ( for many tasks )

**Comment by djalova** [comment]
@gilv I tested this out and only the first task does the init, the subsequent tasks just pull from the cache.

**Comment by djalova** [comment]
@gilv Also with a singleton isn't there be an issue if the user accesses 2 different services? For example reading from a public object storage and writing to their private storage would require 2 different instances of an IStoreClient.

**Comment by djalova** [comment]
Here's the relevant part of the logs
```
16/12/07 10:59:20 INFO Executor: Using REPL class URI: spark://127.0.0.1:63214/classes
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 0
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 1
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 2
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 3
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 4
16/12/07 10:59:41 INFO CoarseGrainedExecutorBackend: Got assigned task 5
16/12/07 10:59:41 INFO Executor: Running task 2.0 in stage 0.0 (TID 2)
16/12/07 10:59:41 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/12/07 10:59:41 INFO Executor: Running task 4.0 in stage 0.0 (TID 4)
16/12/07 10:59:41 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/12/07 10:59:41 INFO Executor: Running task 3.0 in stage 0.0 (TID 3)
16/12/07 10:59:41 INFO Executor: Running task 5.0 in stage 0.0 (TID 5)
16/12/07 10:59:41 INFO Executor: Fetching spark://127.0.0.1:63214/jars/stocator-1.0.8-SNAPSHOT-jar-with-dependencies.jar with timestamp 1481137157996
16/12/07 10:59:41 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:63214 after 1 ms (0 ms spent in bootstraps)
16/12/07 10:59:41 INFO Utils: Fetching spark://127.0.0.1:63214/jars/stocator-1.0.8-SNAPSHOT-jar-with-dependencies.jar to /private/var/folders/5x/v3x7zbnj3lj1rtfmq3_bs7sw0000gn/T/spark-857dc62a-c395-4675-8ea8-4f3fc81a8d8d/executor-c1212fe7-a77f-4a51-b408-dced68dc3ae1/spark-ce085788-3899-459e-98c5-4494d6f653b8/fetchFileTemp6382092271820061866.tmp
16/12/07 10:59:42 INFO Utils: Copying /private/var/folders/5x/v3x7zbnj3lj1rtfmq3_bs7sw0000gn/T/spark-857dc62a-c395-4675-8ea8-4f3fc81a8d8d/executor-c1212fe7-a77f-4a51-b408-dced68dc3ae1/spark-ce085788-3899-459e-98c5-4494d6f653b8/12802680141481137157996_cache to /Users/djalova/IdeaProjects/swift/spark/work/app-20161207105918-0000/0/./stocator-1.0.8-SNAPSHOT-jar-with-dependencies.jar
16/12/07 10:59:42 INFO Executor: Adding file:/Users/djalova/IdeaProjects/swift/spark/work/app-20161207105918-0000/0/./stocator-1.0.8-SNAPSHOT-jar-with-dependencies.jar to class loader
16/12/07 10:59:42 INFO TorrentBroadcast: Started reading broadcast variable 1
16/12/07 10:59:42 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:63216 after 1 ms (0 ms spent in bootstraps)
16/12/07 10:59:42 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1802.0 B, free 457.9 MB)
16/12/07 10:59:42 INFO TorrentBroadcast: Reading broadcast variable 1 took 96 ms
16/12/07 10:59:42 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 2.9 KB, free 457.9 MB)
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts/part-00001-attempt_201612061425_0000_m_000001_1:0+134217653
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts2/part-00002-attempt_201612061430_0001_m_000002_5:0+65519206
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts/part-00002-attempt_201612061425_0000_m_000002_2:0+65519206
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts/part-00000-attempt_201612061425_0000_m_000000_0:0+134217609
16/12/07 10:59:42 INFO TorrentBroadcast: Started reading broadcast variable 0
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts2/part-00000-attempt_201612061430_0001_m_000000_3:0+134217609
16/12/07 10:59:42 INFO HadoopRDD: Input split: swift2d://deleteThis.bmv3/parts2/part-00001-attempt_201612061430_0001_m_000001_4:0+134217653
16/12/07 10:59:42 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 16.0 KB, free 457.9 MB)
16/12/07 10:59:42 INFO TorrentBroadcast: Reading broadcast variable 0 took 9 ms
16/12/07 10:59:42 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 195.8 KB, free 457.7 MB)
16/12/07 10:59:42 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/12/07 10:59:42 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/12/07 10:59:42 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/12/07 10:59:42 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/12/07 10:59:42 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/12/07 10:59:42 INFO ObjectStoreVisitor: Stocator registered as swift2d for swift2d://deleteThis.bmv3/parts/part-00002-attempt_201612061425_0000_m_000002_2
16/12/07 10:59:42 INFO ClientImpl: JOSS / Creating real account instance
16/12/07 10:59:42 INFO ClientImpl: JOSS / * Allow caching: true
16/12/07 10:59:42 INFO ClientImpl: JOSS / Use HTTP client set by client (overrides previous HttpClient settings)
16/12/07 10:59:42 INFO ClientImpl: JOSS / Attempting authentication with tenant name: null, tenant ID: null, username: null, Auth URL: https://identity.open.softlayer.com/v3/auth/tokens
16/12/07 10:59:43 INFO ClientImpl: JOSS / Successfully authenticated
16/12/07 10:59:43 INFO ClientImpl: JOSS / Applying preferred region: dallas
16/12/07 10:59:43 INFO ClientImpl: JOSS / Using TempURL hash prefix source: PUBLIC_URL_PATH
16/12/07 10:59:43 INFO AbstractAccount: JOSS / Use public host: null
16/12/07 10:59:43 INFO AbstractAccount: JOSS / Use private host: null
16/12/07 10:59:43 INFO AbstractAccount: JOSS / Allow Container caching: true
16/12/07 10:59:43 INFO AbstractAccount: JOSS / Allow reauthentication: true
16/12/07 10:59:43 INFO AbstractAccount: JOSS / Setting hash password
16/12/07 11:00:31 INFO Executor: Finished task 5.0 in stage 0.0 (TID 5). 948 bytes result sent to driver
16/12/07 11:00:33 INFO Executor: Finished task 2.0 in stage 0.0 (TID 2). 948 bytes result sent to driver
16/12/07 11:01:14 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 1725 bytes result sent to driver
16/12/07 11:01:16 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 948 bytes result sent to driver
16/12/07 11:01:17 INFO Executor: Finished task 4.0 in stage 0.0 (TID 4). 948 bytes result sent to driver
16/12/07 11:01:17 INFO Executor: Finished task 3.0 in stage 0.0 (TID 3). 1725 bytes result sent to driver
```

**Comment by gilv** [comment]
@djalova I still struggle to understand why cache in has map per stocator init method will improve stocator init from all different tasks that all executed in the same JVM. What exactly you tested that you saw benefit? How many tasks were there and how many workers? What was the number of tasks on each worker node? thanks

**Comment by djalova** [comment]
@gilv I did this with a single worker running 6 tasks. Before the patch, each task would create its own instance of APIClient. The patch adds a cache to be shared across all tasks created by a single worker. If I were to add a new worker then that worker would have its own cache for its tasks. I tested this by reading from a file with multiple partitions so that each partition would be allocated its own task.

**Comment by gilv** [comment]
@djalova I think something is wrong here...
In spark-shell I did 

1. sc.textFile("swift2d://contA.service/*).count()
2. sc.textFile("swift2d://contB.service/*).count()

But in (2) i got results of (1)

**Comment by effi-ofer** [comment]
Gil, the reason this code gets executed once by each executor worker (i.e. JVM) is this code sniplet in getStoreClient()

    if (sClientMap.containsKey(service)) {
      return sClientMap.get(service);
    }

I tested this on my environment and confirmed that the code works.  getStoreClient gets called once per task, but the actual body of the function gets executed only once per JVM.

**Comment by djalova** [comment]
@gilv Good point. I made a mistake and cached by the service name only. I should cache by container and service name. I will fix this soon.

**Pull request closed without merging**
