### PR TITLE
Add external auth provider

### PR DESCRIPTION
**Pull request by XciD**
- Adding External auth provider for Swift Authentification. 
- Removing the Keystone_V3 implemented in stocator and use the one provided by JOSS:

About the Keystone V3 implemented by stocator, I've found a bug. In fact, to connect to Keystone you can use either the `tenant_name` or the `tenant_id`. In your code, you take the `tenant_id` and put it on the `tenant_name`. So we add to implement some logic to change our secrets just for stocator.
So, has I was on the code base, I tought that I will fix it.
If you thing this deserve another PR, please let me know.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@XciD thanks for this pull request.  I am glad to know that Stocator-Swift is still used out there. We now mostly focus on the Stocator-COS which expose S3 API and Swift extension is not actively developed.  Can you explain please what you changed in this pull request? I usually prefer that new code doesn't change previous behaviour and seems it's not the case in this pull request, right? For you example you removed KEYSTONE_V3_AUTH and other things. Is this correct?

**Comment by XciD** [comment]
Hello @gilv 

I'm sorry, I've miss some point in my PR description. I've edited it.

**Comment by gilv** [comment]
@XciD thanks. let me review it a bit and then i will merge it.

**Comment by gilv** [comment]
@XciD thanks. merged

**Pull request closed without merging**
