### PR TITLE
fixDynamicPartitionInsert

### PR DESCRIPTION
**Pull request by yangchenghuang**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@yangchenghuang thanks a lot. I will run some tests to see it didn't break anything and then i will merge it

**Comment by gilv** [comment]
@yangchenghuang can you please commit this pull request against master branch? I will then merge it into cos-sdk branch by myself. Thanks

**Comment by yangchenghuang** [comment]
> @yangchenghuang can you please commit this pull request against master branch? I will then merge it into cos-sdk branch by myself. Thanks

@gilv Thanks! I will commit the pull request against the master branch tomorrow.

**Comment by gilv** [comment]
@yangchenghuang will you handle it please?

**Comment by yangchenghuang** [comment]
> @yangchenghuang will you handle it please?

@gilv Apologies for the delay. Created.

**Comment by gilv** [comment]
@yangchenghuang thanks. merged

**Pull request closed without merging**
