### PR TITLE
guava version change to 30.0 and httpclient version change to 5.0.3

### PR DESCRIPTION
**Pull request by rachnajain-ibm**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by rachnajain-ibm** [comment]
@gilv 

This is a new and a cumulative changes PR against the previous PRs which were causing conflict with the master, viz:

[https://github.com/CODAIT/stocator/pull/281](url)
[https://github.com/CODAIT/stocator/pull/282](url)
[https://github.com/CODAIT/stocator/pull/283](url)

**Comment by gilv** [comment]
@rachnajain-ibm this patch fails with cos-sdk branch, Can you check it please?

**Comment by gilv** [comment]
@rachnajain-ibm getting
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/gilv/Dev/stocator/src/main/java/com/ibm/stocator/fs/swift/http/SwiftConnectionManager.java:[120,48] cannot find symbol
  symbol:   method setNormalizeUri(boolean)
  location: class org.apache.http.client.config.RequestConfig.Builder
[ERROR] /Users/gilv/Dev/stocator/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIDirect.java:[159,9] cannot find symbol
  symbol:   method setNormalizeUri(boolean)
  location: class org.apache.http.client.config.RequestConfig.Builder
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.500 s
[INFO] Finished at: 2021-06-01T21:21:52+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project stocator: Compilation failure: Compilation failure: 
[ERROR] /Users/gilv/Dev/stocator/src/main/java/com/ibm/stocator/fs/swift/http/SwiftConnectionManager.java:[120,48] cannot find symbol
[ERROR]   symbol:   method setNormalizeUri(boolean)
[ERROR]   location: class org.apache.http.client.config.RequestConfig.Builder
[ERROR] /Users/gilv/Dev/stocator/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIDirect.java:[159,9] cannot find symbol
[ERROR]   symbol:   method setNormalizeUri(boolean)
[ERROR]   location: class org.apache.http.client.config.RequestConfig.Builder
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
gilv1-mac:stocator gilv$ mvn clean package
```

**Comment by gilv** [comment]
@rachnajain-ibm merged. thanks. no more issues

**Pull request closed without merging**
